version: '3.8'
services:
  mongodb:
    image: mongo:6.0.4
    restart: always
    ports:
      - "27017:27017"
    networks:
      - cdq
    volumes:
      - mongodb-data:/data/db
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - cdq
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

volumes:
  mongodb-data:
networks:
  cdq:
    driver: bridge